# Generated by Django 4.2.13 on 2026-05-29 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(db_index=True, max_length=1000, unique=True, verbose_name='Desafío (Challenge)')),
                ('challenge_type', models.CharField(choices=[('register', 'Registro'), ('authenticate', 'Autenticación')], max_length=20, verbose_name='Tipo de Desafío')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('is_used', models.BooleanField(default=False, help_text='Indica si el desafío ya ha sido consumido', verbose_name='Utilizado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Desafío WebAuthn',
                'verbose_name_plural': 'Desafíos WebAuthn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(db_index=True, max_length=1000, unique=True, verbose_name='ID de Credencial')),
                ('public_key', models.TextField(help_text='Clave pública en formato JSON codificada', verbose_name='Clave Pública (JSON)')),
                ('sign_count', models.IntegerField(default=0, help_text='Contador para detectar clonación de autenticadores', verbose_name='Contador de Firma')),
                ('transports', models.CharField(blank=True, help_text='Transportes disponibles: usb, nfc, ble, internal', max_length=500, verbose_name='Transportes')),
                ('aaguid', models.CharField(blank=True, help_text='Identificador único del modelo de autenticador', max_length=36, verbose_name='AAGUID')),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo del dispositivo biométrico', max_length=255, verbose_name='Nombre del Dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Utilización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la credencial está habilitada', verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Credencial WebAuthn',
                'verbose_name_plural': 'Credenciales WebAuthn',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'credential_id')},
            },
        ),
    ]
