# Generated by Django 4.2.13 on 2026-05-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], default='CC', max_length=2, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(help_text='Debe ser único en el sistema', max_length=20, unique=True, verbose_name='Número de documento')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('blood_type', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='Tipo de sangre')),
                ('allergies', models.TextField(blank=True, help_text='Descripción de alergias conocidas', verbose_name='Alergias')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Enfermedades crónicas o condiciones médicas', verbose_name='Enfermedades crónicas')),
                ('clinical_notes', models.JSONField(blank=True, default=list, help_text='Registro de notas clínicas en formato JSON', verbose_name='Notas clínicas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_number'], name='pacientes_p_documen_60a414_idx'), models.Index(fields=['first_name', 'last_name'], name='pacientes_p_first_n_d57730_idx'), models.Index(fields=['-created_at'], name='pacientes_p_created_faf69f_idx')],
            },
        ),
    ]
