# Generated by Django 4.2.13 on 2026-05-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='document_number',
            field=models.CharField(db_index=True, help_text='Debe ser único en el sistema', max_length=20, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
