# Generated by Django 4.2.13 on 2026-05-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_patient_document_number_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Rango válido: 1900-2099', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinical_notes',
            field=models.JSONField(blank=True, default=list, help_text='Registro de notas clínicas. Acepta lista de objetos JSON o texto plano (se convierte automáticamente)', verbose_name='Notas clínicas'),
        ),
    ]
