# Generated by Django 4.2.13 on 2026-05-29 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_patient_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdi', models.IntegerField(help_text='Número identificador del diente (11-48)', verbose_name='Número FDI')),
                ('status', models.CharField(choices=[('S', 'Sano'), ('C', 'Caries'), ('R', 'Restaurado'), ('E', 'Extracción')], default='S', max_length=1, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas / Observaciones')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='pacientes.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro de Diente',
                'verbose_name_plural': 'Registros de Dientes',
                'ordering': ['fdi'],
                'unique_together': {('patient', 'fdi')},
            },
        ),
    ]
